version: '3.8'

services:
#  kafka:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.stats().ok" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - billion-network


volumes:
  mongodb_data:

networks:
  billion-network:
    driver: bridge