app:
  name: 'billion-producer-service'
  version: '1.0.0'

logger:
  level: 2

mongo:
  url: mongodb://localhost:27017
  db_name: 'db'

kafka:
  url: amqp://guest:guest@localhost:5672/

collections:
  temp_datas: 'datas'

settings: